/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-06-02 02:32:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinmember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1617260074751L));
    _jspx_dependants.put("jar:file:/D:/src/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AdminProjects_f/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<title>Registration - ClassiGrids Classified Ads and Listing Website Template</title>\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/images/favicon.svg\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Lato&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/LineIcons.2.0.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/animate.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/tiny-slider.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/glightbox.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/join.css\" />\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("      <p class=\"browserupgrade\">\r\n");
      out.write("        You are using an <strong>outdated</strong> browser. Please\r\n");
      out.write("        <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve\r\n");
      out.write("        your experience and security.\r\n");
      out.write("      </p>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"preloader\">\r\n");
      out.write("<div class=\"preloader-inner\">\r\n");
      out.write("<div class=\"preloader-icon\">\r\n");
      out.write("<span></span>\r\n");
      out.write("<span></span>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"header navbar-area\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("<div class=\"col-lg-12\">\r\n");
      out.write("<div class=\"nav-inner\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("<a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("<img src=\"resources/images/logo2.png\" alt=\"Logo\">\r\n");
      out.write("</a>\r\n");
      out.write("<button class=\"navbar-toggler mobile-menu-btn\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("<span class=\"toggler-icon\"></span>\r\n");
      out.write("<span class=\"toggler-icon\"></span>\r\n");
      out.write("<span class=\"toggler-icon\"></span>\r\n");
      out.write("</button>\r\n");
      out.write("<div class=\"collapse navbar-collapse sub-menu-bar\" id=\"navbarSupportedContent\">\r\n");
      out.write("<ul id=\"nav\" class=\"navbar-nav ms-auto\">\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a class=\" dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-1\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">Home</a>\r\n");
      out.write("<ul class=\"sub-menu collapse\" id=\"submenu-1-1\">\r\n");
      out.write("<li class=\"nav-item\"><a href=\"index.html\">Home Default</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"index2.html\">Home Version 2</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"index3.html\">Home Version 3</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write(" <a href=\"category.html\" aria-label=\"Toggle navigation\">Categories</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a class=\" dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-3\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">Listings</a>\r\n");
      out.write("<ul class=\"sub-menu collapse\" id=\"submenu-1-3\">\r\n");
      out.write("<li class=\"nav-item\"><a href=\"item-listing-grid.html\">Ad Grid</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"item-listing-list.html\">Ad Listing</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"item-details.html\">Ad Details</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a class=\" active dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-4\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">Pages</a>\r\n");
      out.write("<ul class=\"sub-menu mega-menu collapse\" id=\"submenu-1-4\">\r\n");
      out.write("<li class=\"single-block\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li class=\"mega-menu-title\">Essential Pages</li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"about-us.html\">About Us</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"item-details.html\">Ads Details</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"post-item.html\">Ads Post</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"pricing.html\">Pricing Table</a></li>\r\n");
      out.write("<li class=\"nav-item active\"><a href=\"registration.html\">Sign Up</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"login.html\">Sign In</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"faq.html\">FAQ</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"404.html\">Error Page</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"mail-success.html\">Mail Success</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"coming-soon.html\">Comming Soon</a>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"single-block\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li class=\"mega-menu-title\">Dashboard</li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"dashboard.html\">Account Overview</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"profile-settings.html\">My Profile</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"my-items.html\">My Ads</a></li>\r\n");
      out.write(" <li class=\"nav-item\"><a href=\"favourite-items.html\">Favorite Ads</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"post-item.html\">Ad post</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"bookmarked-items.html\">Bookmarked Ad</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"messages.html\">Messages</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"delete-account.html\">Close account</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"invoice.html\">Invoice</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a class=\" dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-5\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">Blog</a>\r\n");
      out.write("<ul class=\"sub-menu collapse\" id=\"submenu-1-5\">\r\n");
      out.write("<li class=\"nav-item\"><a href=\"blog-grid-sidebar.html\">Blog Grid Sidebar</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"blog-single.html\">Blog Single</a></li>\r\n");
      out.write("<li class=\"nav-item\"><a href=\"blog-single-sidebar.html\">Blog Single\r\n");
      out.write("Sibebar</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div> \r\n");
      out.write("<div class=\"login-button\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"login.do\"><i class=\"lni lni-enter\"></i> Login</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"join.html\"><i class=\"lni lni-user\"></i> Register</a>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"button header-button\">\r\n");
      out.write("<a href=\"post-item.html\" class=\"btn\">Post an Ad</a>\r\n");
      out.write("</div>\r\n");
      out.write("</nav> \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div> \r\n");
      out.write("</div> \r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"breadcrumbs\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("<div class=\"breadcrumbs-content\">\r\n");
      out.write("<h1 class=\"page-title\">회원가입</h1>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("<ul class=\"breadcrumb-nav\">\r\n");
      out.write("<li><a href=\".\">홈</a></li>\r\n");
      out.write("<li>회원가입</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"login registration section\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-12\">\r\n");
      out.write("<div class=\"form-head\">\r\n");
      out.write("<h4 class=\"title\">회원가입</h4>\r\n");
      out.write("<div class=\"socila-login\">\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"join.do\" id=\"join_form\" method=\"post\">\r\n");
      out.write("<div class=\"form-group\">아이디\r\n");
      out.write("<input class=\"id_input\" name=\"id\" type=\"text\">\r\n");
      out.write("<span class=\"id_input_re_1\">사용 가능한 아이디입니다.</span>\r\n");
      out.write("<span class=\"id_input_re_2\">아이디가 이미 존재합니다.</span>\r\n");
      out.write("<span class=\"final_id_ck\">아이디를 입력해주세요.</span>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>비밀번호</label>\r\n");
      out.write("<input class=\"pw_input\" name=\"pwd\" type=\"password\">\r\n");
      out.write("<span class=\"final_pw_ck\">비밀번호를 입력해주세요.</span>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>비밀번호 확인</label>\r\n");
      out.write("<input class=pwck_input type=\"password\">\r\n");
      out.write("<span class=\"final_pwck_ck\">비밀번호 확인을 입력해주세요.</span>\r\n");
      out.write("<span class=\"pwck_input_re_1\">비밀번호가 일치합니다.</span>\r\n");
      out.write("<span class=\"pwck_input_re_2\">비밀번호가 일치하지 않습니다.</span>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>이름</label>\r\n");
      out.write("<div>\r\n");
      out.write("<input class=\"user_input\" name=\"name\" type=\"text\">\r\n");
      out.write("</div>\r\n");
      out.write("<span class=\"final_name_ck\">이름을 입력해주세요.</span>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"mail_wrap\">\r\n");
      out.write("\t<div class=\"mail_name\">이메일</div>\r\n");
      out.write("\t<div class=\"mail_input_box\">\r\n");
      out.write("\t\t<input class=\"mail_input\" name=\"email\" type=\"email\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<span class=\"final_mail_ck\">이메일을 입력해주세요.</span>\r\n");
      out.write("\t     <div class=\"mail_check_wrap\">\r\n");
      out.write("                    <div class=\"mail_check_input_box\" id=\"mail_check_input_box_false\">\r\n");
      out.write("                        <input class=\"mail_check_input\" disabled=\"disabled\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mail_check_button\">\r\n");
      out.write("                        <span>인증번호 전송</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t                    <div class=\"clearfix\"></div>\r\n");
      out.write("\t                    <span class=\"final_mailnum_ck\" id=\"mail_check_input_box_warn\" >인증번호를 입력해주세요.</span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t               </div>\r\n");
      out.write("\t               \r\n");
      out.write("<div class=\"form-group\"> \r\n");
      out.write("<label for=\"mem_phone\">전화번호</label> \r\n");
      out.write("<input type=\"tel\" class=\"phone_input\" id=\"mem_phone\" name=\"tel\" placeholder=\"'-'없이 번호만 입력해주세요\"> \r\n");
      out.write("<span class=\"final_phone_ck\">전화번호를 입력해주세요.</span>\r\n");
      out.write("<div class=\"eheck_font\" id=\"phone_check\"></div> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- <select name = \"ad\"> -->\r\n");
      out.write("<!-- \t<option value=\"강남구\">강남구</option> -->\r\n");
      out.write("<!-- \t<option value=\"강동구\">강동구</option> -->\r\n");
      out.write("<!-- \t<option value=\"강북구\">강북구</option> -->\r\n");
      out.write("<!-- \t<option value=\"강서구\">강서구</option> -->\r\n");
      out.write("<!-- \t<option value=\"관악구\">관악구</option> -->\r\n");
      out.write("<!-- \t<option value=\"광진구\">광진구</option> -->\r\n");
      out.write("<!-- \t<option value=\"구로구\">구로구</option> -->\r\n");
      out.write("<!-- \t<option value=\"금천구\">금천구</option> -->\r\n");
      out.write("<!-- \t<option value=\"노원구\">노원구</option> -->\r\n");
      out.write("<!-- \t<option value=\"도봉구\">도봉구</option> -->\r\n");
      out.write("<!-- \t<option value=\"동대문구\">동대문구</option> -->\r\n");
      out.write("<!-- \t<option value=\"동작구\">동작구</option> -->\r\n");
      out.write("<!-- \t<option value=\"마포구\">마포구</option> -->\r\n");
      out.write("<!-- \t<option value=\"서대문구\">서대문구</option> -->\r\n");
      out.write("<!-- \t<option value=\"서초구\">서초구</option> -->\r\n");
      out.write("<!-- \t<option value=\"성동구\">성동구</option> -->\r\n");
      out.write("<!-- \t<option value=\"성북구\">성북구</option> -->\r\n");
      out.write("<!-- \t<option value=\"송파구\">송파구</option> -->\r\n");
      out.write("<!-- \t<option value=\"양천구\">양천구</option>\t\t\t\t  -->\r\n");
      out.write("<!-- \t<option value=\"영등포구\">영등포구</option> -->\r\n");
      out.write("<!-- \t<option value=\"용산구\">용산구</option> -->\r\n");
      out.write("<!-- \t<option value=\"은평구\">은평구</option> -->\r\n");
      out.write("<!-- \t<option value=\"종로구\">종로구</option> -->\r\n");
      out.write("<!-- \t<option value=\"중구\">중구</option> -->\r\n");
      out.write("<!-- \t<option value=\"중랑구\">중랑구</option> -->\r\n");
      out.write("<!-- </select> -->\r\n");
      out.write("\r\n");
      out.write("<label>주소</label>\r\n");
      out.write("<div class=\"form-group\"> \r\n");
      out.write("<input class=\"form-control\" style=\"width: 40%; display: inline;\" placeholder=\"우편번호\" name=\"oAdd\" id=\"mem_oaddress\" type=\"text\" readonly=\"readonly\" > \r\n");
      out.write("<button type=\"button\" class=\"btn btn-default\" onclick=\"execPostCode();\"><i class=\"fa fa-search\"></i> 우편번호 찾기</button>\r\n");
      out.write("<!--  <button type=\"button\" style=\"background :gray; width: 40%; display: inline;\"onclick=\"execPostCode();\">우편번호 찾기</button>--> \r\n");
      out.write("</div> \r\n");
      out.write("<div class=\"form-group\"> <input class=\"form-control\" style=\"top: 5px;\" placeholder=\"주소\" name=\"add\" id=\"mem_address\" type=\"text\" readonly=\"readonly\" /> \r\n");
      out.write("</div> \r\n");
      out.write("<div class=\"form-group\"> \r\n");
      out.write("<input class=\"address_input_3\" placeholder=\"상세주소\" name=\"detailAdd\" id=\"mem_detailaddress\" type=\"text\" /> \r\n");
      out.write("<!-- <input type=\"text\" id=\"mem_extraAddress\" placeholder=\"참고항목\"> -->\r\n");
      out.write("<span class=\"final_addr_ck\">상세 주소를 입력해주세요.</span>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"type_input\">\r\n");
      out.write("<label>구매자로 가입</label>\r\n");
      out.write("<input type=\"radio\" name=\"who\" id=\"sel\" value=\"1\"/><br>\r\n");
      out.write("<label>판매자로 가입</label>\r\n");
      out.write("<input type=\"radio\" name=\"who\" id=\"cus\" value=\"2\"/>\r\n");
      out.write("<span class=\"final_type_ck\">타입을 선택해주세요.</span>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("    function execPostCode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("      //          if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("      //              if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("      //                  extraAddr += data.bname;\r\n");
      out.write("      //              }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("      //              if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("       //                 extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("     //               }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("       //             if(extraAddr !== ''){\r\n");
      out.write("    //                    extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("      //              }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("              //     document.getElementById(\"mem_extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("   //             } else {\r\n");
      out.write("               //     document.getElementById(\"mem_extraAddress\").value = '';\r\n");
      out.write("      //          }\r\n");
      out.write("//\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById(\"mem_oaddress\").value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"mem_address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"mem_detailaddress\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- <div class=\"check-and-pass\"> -->\r\n");
      out.write("<!-- <div class=\"row align-items-center\"> -->\r\n");
      out.write("<!-- <div class=\"col-12\"> -->\r\n");
      out.write("<!-- <div class=\"form-check\"> -->\r\n");
      out.write("<!-- <input type=\"checkbox\" class=\"form-check-input width-auto\" id=\"exampleCheck1\"> -->\r\n");
      out.write("<!-- <label class=\"form-check-label\">동의하십니까? <a href=\"javascript:void(0)\">계약 조건</a></label> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<div class=\"button\">\r\n");
      out.write("\t<input type=\"submit\" class=\"join_button1\" value=\"가입하기\">\r\n");
      out.write("\t<!--<button type=\"submit\" class=\"btn\">회원등록</button> -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("<p class=\"outer-link\">이미 계정이 있나요? <a href=\"login.do\">로그인하기</a>\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"scroll-top btn-hover\">\r\n");
      out.write("<i class=\"lni lni-chevron-up\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<script data-cfasync=\"false\" src=\"resources/js/email-decode.min.js\"></script><script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/wow.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/tiny-slider.js\"></script>\r\n");
      out.write("<script src=\"resources/js/glightbox.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var code=\"\";\r\n");
      out.write("\r\n");
      out.write("/* 유효성 검사 통과유무 변수 */\r\n");
      out.write("var idCheck = false;            // 아이디\r\n");
      out.write("var idckCheck = false;            // 아이디 중복 검사\r\n");
      out.write("var pwCheck = false;            // 비번\r\n");
      out.write("var pwckCheck = false;            // 비번 확인\r\n");
      out.write("var pwckcorCheck = false;        // 비번 확인 일치 확인\r\n");
      out.write("var nameCheck = false;            // 이름\r\n");
      out.write("var mailCheck = false;            // 이메일\r\n");
      out.write("var mailnumCheck = false;        // 이메일 인증번호 확인\r\n");
      out.write("var phoneCheck = false; \t\t\t//전화번호\r\n");
      out.write("var addressCheck = false;        // 주소\r\n");
      out.write("var typeCheck = false; \t\t\t//타입\r\n");
      out.write("var sel= document.getElementById(\"sel\");\r\n");
      out.write("var mas= document.getElementById(\"mas\");\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("$(\".join_button\").click(function(){\r\n");
      out.write("    \r\n");
      out.write("    /* 입력값 변수 */\r\n");
      out.write("    var id = $('.id_input').val();                 // id 입력란\r\n");
      out.write("    var pw = $('.pw_input').val();                // 비밀번호 입력란\r\n");
      out.write("    var pwck = $('.pwck_input').val();            // 비밀번호 확인 입력란\r\n");
      out.write("    var name = $('.user_input').val();            // 이름 입력란\r\n");
      out.write("    var mail = $('.mail_input').val();            // 이메일 입력란\r\n");
      out.write("    var mailnum = $('.mail_check_input').val();\r\n");
      out.write("    var phone = $('.phone_input').val();  \t\t\t// 전화번호 입력란\r\n");
      out.write("    var addr = $('.address_input_3').val();        // 주소 입력란\r\n");
      out.write("    var type = $('.type_input').val(); \t\t//타입 입력란\r\n");
      out.write("    /* 아이디 유효성검사 */\r\n");
      out.write("    if(id == \"\"){\r\n");
      out.write("        $('.final_id_ck').css('display','block');\r\n");
      out.write("        idCheck = false;\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.final_id_ck').css('display', 'none');\r\n");
      out.write("        idCheck = true;\r\n");
      out.write("    }\r\n");
      out.write("    /* 비밀번호 유효성 검사 */\r\n");
      out.write("    if(pw == \"\"){\r\n");
      out.write("        $('.final_pw_ck').css('display','block');\r\n");
      out.write("        pwCheck = false;\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.final_pw_ck').css('display', 'none');\r\n");
      out.write("        pwCheck = true;\r\n");
      out.write("    }\r\n");
      out.write("    /* 비밀번호 확인 유효성 검사 */\r\n");
      out.write("    if(pwck == \"\"){\r\n");
      out.write("        $('.final_pwck_ck').css('display','block');\r\n");
      out.write("        pwckCheck = false;\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.final_pwck_ck').css('display', 'none');\r\n");
      out.write("        pwckCheck = true;\r\n");
      out.write("    }\r\n");
      out.write("    /* 이름 유효성 검사 */\r\n");
      out.write("    if(name == \"\"){\r\n");
      out.write("        $('.final_name_ck').css('display','block');\r\n");
      out.write("        nameCheck = false;\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.final_name_ck').css('display', 'none');\r\n");
      out.write("        nameCheck = true;\r\n");
      out.write("    }\r\n");
      out.write("    /* 이메일 유효성 검사 */\r\n");
      out.write("    if(mail == \"\"){\r\n");
      out.write("        $('.final_mail_ck').css('display','block');\r\n");
      out.write("        mailCheck = false;\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.final_mail_ck').css('display', 'none');\r\n");
      out.write("        mailCheck = true;\r\n");
      out.write("    }\r\n");
      out.write("    /* 인증번호 유효성 검사 */\r\n");
      out.write("    if(mailnum == \"\"){\r\n");
      out.write("        $('.final_mailnum_ck').css('display','block');\r\n");
      out.write("        mailnumCheck = false;\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.final_mailnum_ck').css('display', 'none');\r\n");
      out.write("        mailnumCheck = true;\r\n");
      out.write("    }\r\n");
      out.write("    /* 전화번호 유효성 검사 */\r\n");
      out.write("    if(phone == \"\"){\r\n");
      out.write("        $('.final_phone_ck').css('display','block');\r\n");
      out.write("        phoneCheck = false;\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.final_phone_ck').css('display', 'none');\r\n");
      out.write("        phoneCheck = true;\r\n");
      out.write("    }\r\n");
      out.write("    /* 주소 유효성 검사 */\r\n");
      out.write("    if(addr == \"\"){\r\n");
      out.write("        $('.final_addr_ck').css('display','block');\r\n");
      out.write("        addressCheck = false;\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.final_addr_ck').css('display', 'none');\r\n");
      out.write("        addressCheck = true;\r\n");
      out.write("    }\r\n");
      out.write("    /* 타입 유효성 검사 */\r\n");
      out.write("    if(!sel.checked && !cus.checked) {\r\n");
      out.write("    \t $('.final_type_ck').css('display','block');\r\n");
      out.write("\t       typeCheck = false;\r\n");
      out.write("    } else{\r\n");
      out.write("      $('.final_type_ck').css('display', 'none');\r\n");
      out.write("      typeCheck = true;\r\n");
      out.write("  }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("//     if(type == \"\"){\r\n");
      out.write("//         $('.final_type_ck').css('display','block');\r\n");
      out.write("//         typeCheck = false;\r\n");
      out.write("//     }else{\r\n");
      out.write("//         $('.final_type_ck').css('display', 'none');\r\n");
      out.write("//         typeCheck = true;\r\n");
      out.write("//     }\r\n");
      out.write("    /* 최종 유효성 검사 */\r\n");
      out.write("    if(idCheck&&idckCheck&&pwCheck&&pwckCheck&&pwckcorCheck&&nameCheck&&mailCheck&&mailnumCheck&&phoneCheck&&addressCheck&&typeCheck) {\r\n");
      out.write("    \tdocument.getElementById('join_form').submit();\r\n");
      out.write("   \t    alert(document.getElementById(\"join_form\").tagName);\r\n");
      out.write("        location.href=\".\";\r\n");
      out.write("        return false;\r\n");
      out.write("\r\n");
      out.write("    } else {\r\n");
      out.write("    \talert(\"빈칸을 채워주세요!!\");\r\n");
      out.write("    }      \r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("//아이디 중복검사\r\n");
      out.write("$('.id_input').on(\"propertychange change keyup paste input\", function(){\r\n");
      out.write("\r\n");
      out.write("/*\tconsole.log(\"id 중복 테스트\"); */\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar id = $('.id_input').val();\t\t\t// .id_input에 입력되는 값\r\n");
      out.write("\tvar data = {id : id}\t\t\t\t// '컨트롤에 넘길 데이터 이름' : '데이터(.id_input에 입력되는 값)'\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\turl : \"memberIdChk\",\r\n");
      out.write("\t\tdata : data,\r\n");
      out.write("\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\tconsole.log(\"성공 여부\" + result);\r\n");
      out.write("\t\t\tif(result != 'fail'){\r\n");
      out.write("\t\t\t\t$('.id_input_re_1').css(\"display\",\"inline-block\");\r\n");
      out.write("\t\t\t\t$('.id_input_re_2').css(\"display\", \"none\");\t\r\n");
      out.write("\t\t\t\t// 아이디 중복이 없는 경우\r\n");
      out.write("\t\t\t\tidckCheck = true;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('.id_input_re_2').css(\"display\",\"inline-block\");\r\n");
      out.write("\t\t\t\t$('.id_input_re_1').css(\"display\", \"none\");\t\t\t\t\r\n");
      out.write("\t\t\t\t// 아이디 중복된 경우\r\n");
      out.write("\t\t\t\tidckCheck = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} //success 종료\r\n");
      out.write("\t}); // ajax 종료\r\n");
      out.write("});// function 종료\r\n");
      out.write("/* 인증번호 이메일 전송 */\r\n");
      out.write("$(\".mail_check_button\").click(function(){\r\n");
      out.write("\tvar mem_email = $(\".mail_input\").val();            // 입력한 이메일\r\n");
      out.write("    var cehckBox = $(\".mail_check_input\");        // 인증번호 입력란\r\n");
      out.write("    var boxWrap = $(\".mail_check_input_box\");    // 인증번호 입력란 박스 \r\n");
      out.write(" $.ajax({\r\n");
      out.write("        \r\n");
      out.write("        type:\"GET\",\r\n");
      out.write("        url:\"mailCheck?mem_email=\" + mem_email,\r\n");
      out.write("        success:function(data){\r\n");
      out.write("            \r\n");
      out.write("        \t//console.log(\"data : \" + data);\r\n");
      out.write("            cehckBox.attr(\"disabled\",false);\r\n");
      out.write("   \t       boxWrap.attr(\"id\", \"mail_check_input_box_true\");\r\n");
      out.write("            code = data;\r\n");
      out.write("        }\r\n");
      out.write("                \r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 인증번호 비교 */\r\n");
      out.write("$(\".mail_check_input\").blur(function(){\r\n");
      out.write("\t  var inputCode = $(\".mail_check_input\").val();        // 입력코드    \r\n");
      out.write("\t    var checkResult = $(\"#mail_check_input_box_warn\");    // 비교 결과     \r\n");
      out.write("\t    \r\n");
      out.write("\t    if(inputCode == code){                            // 일치할 경우\r\n");
      out.write("\t        checkResult.html(\"인증번호가 일치합니다.\");\r\n");
      out.write("\t        checkResult.attr(\"class\", \"correct\");     \r\n");
      out.write("\t        mailnumCheck = true;     // 일치할 경우\r\n");
      out.write("\t    } else {                                            // 일치하지 않을 경우\r\n");
      out.write("\t        checkResult.html(\"인증번호를 다시 확인해주세요.\");\r\n");
      out.write("\t        checkResult.attr(\"class\", \"incorrect\");\r\n");
      out.write("\t        mailnumCheck = false;    // 일치하지 않을 경우\r\n");
      out.write("\t    }    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 비밀번호 확인 일치 유효성 검사 */\r\n");
      out.write(" \r\n");
      out.write("$('.pwck_input').on(\"propertychange change keyup paste input\", function(){\r\n");
      out.write("\tvar pw = $('.pw_input').val();\r\n");
      out.write("    var pwck = $('.pwck_input').val();\r\n");
      out.write("    $('.final_pwck_ck').css('display', 'none'); \r\n");
      out.write("    \r\n");
      out.write("    if(pw == pwck){\r\n");
      out.write("        $('.pwck_input_re_1').css('display','block');\r\n");
      out.write("        $('.pwck_input_re_2').css('display','none');\r\n");
      out.write("        pwckcorCheck = true;\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.pwck_input_re_1').css('display','none');\r\n");
      out.write("        $('.pwck_input_re_2').css('display','block');\r\n");
      out.write("        pwckcorCheck = false;\r\n");
      out.write("    }   \r\n");
      out.write("});    \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
