/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-06-02 02:23:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.yogi.hoxy.dtos.*;
import java.util.Map;
import java.util.List;
import com.yogi.hoxy.utils.Utils;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1617260074751L));
    _jspx_dependants.put("jar:file:/D:/src/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AdminProjects_f/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/src/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AdminProjects_f/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.yogi.hoxy.dtos");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.yogi.hoxy.utils.Utils");
    _jspx_imports_classes.add("java.util.Map");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<title>Ads Details - ClassiGrids Classified Ads and Listing Website Template</title>\r\n");
 List<Map<String, Integer>> list = (List<Map<String, Integer>>) request.getAttribute("list"); 
      out.write('\r');
      out.write('\n');
 ProductDto dto = (ProductDto) request.getAttribute("dto"); 
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/images/favicon.svg\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Lato&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/LineIcons.2.0.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/animate.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/tiny-slider.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/glightbox.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/main.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("      <p class=\"browserupgrade\">\r\n");
      out.write("        You are using an <strong>outdated</strong> browser. Please\r\n");
      out.write("        <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve\r\n");
      out.write("        your experience and security.\r\n");
      out.write("      </p>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"preloader\">\r\n");
      out.write("<div class=\"preloader-inner\">\r\n");
      out.write("<div class=\"preloader-icon\">\r\n");
      out.write("<span></span>\r\n");
      out.write("<span></span>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"header navbar-area\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("<div class=\"col-lg-12\">\r\n");
      out.write("<div class=\"nav-inner\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("<a class=\"navbar-brand\" href=\".\">\r\n");
      out.write("<img src=\"upload/logo.jpg\" alt=\"Logo\">\r\n");
      out.write("</a>\r\n");
      out.write("<button class=\"navbar-toggler mobile-menu-btn\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("<span class=\"toggler-icon\"></span>\r\n");
      out.write("<span class=\"toggler-icon\"></span>\r\n");
      out.write("<span class=\"toggler-icon\"></span>\r\n");
      out.write("</button>\r\n");
      out.write("<div class=\"collapse navbar-collapse sub-menu-bar\" id=\"navbarSupportedContent\">\r\n");
      out.write("<ul id=\"nav\" class=\"navbar-nav ms-auto\">\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\".\" aria-label=\"Toggle navigation\">홈</a>\r\n");
      out.write("</li>\r\n");
      out.write(" <li class=\"nav-item\">\r\n");
      out.write("<a href=\"search.do\" aria-label=\"Toggle navigation\">카테고리</a>\r\n");
      out.write("</li>\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</div> \r\n");
      out.write("<div class=\"login-button\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li>\r\n");
      out.write("<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </p>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"logout.do\"><i class=\"fas fa-sign-out-alt\"></i> 로그아웃</a>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</nav> \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div> \r\n");
      out.write("</div> \r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"breadcrumbs\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("<div class=\"breadcrumbs-content\">\r\n");
      out.write("<h1 class=\"page-title\">상품 상세보기</h1>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("<ul class=\"breadcrumb-nav\">\r\n");
      out.write("<li><a href=\".\">Home</a></li>\r\n");
      out.write("<li>상품 상세보기</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"item-details section\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"top-area\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-lg-6 col-md-12 col-12\">\r\n");
      out.write("<div class=\"product-images\">\r\n");
      out.write("<main id=\"gallery\">\r\n");
      out.write("<div class=\"main-img\">\r\n");
      out.write("<img src=\"upload/product/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.img_Url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"img\" alt=\"#\">\r\n");
      out.write("</div>\r\n");
      out.write("</main>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-6 col-md-12 col-12\">\r\n");
      out.write("<div class=\"product-info\">\r\n");
      out.write("<h2 class=\"title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.productName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("<p class=\"location\"><i class=\"lni lni-map-marker\"></i><a href=\"javascript:void(0)\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.shopDto.local }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></p>\r\n");
      out.write("<h3 class=\"price\">");
      out.print(Utils.comma(dto.getPrice()));
      out.write("원</h3>\r\n");
      out.write("<div class=\"list-info\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li><span>매장: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.shopDto.shopName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("<li><span>카테고리: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("<li><span>재고: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.stock }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개</span></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"contact-info\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li>\r\n");
 boolean isS = false;
   int likes = 0;
for(Map<String, Integer> count : list){
   if(Integer.parseInt(String.valueOf(count.get("product_seq"))) == dto.getProduct_seq()){
      isS = true;
      likes = Integer.parseInt(String.valueOf(count.get("count")));
   }
}   
   if(isS){
      
      out.write("<a href=\"javascript:void(0)\" class=\"mail\">");
      out.print(likes);
      out.write("♥</a>");

   } else {
      
      out.write("<a href=\"javascript:void(0)\" class=\"mail\">0♥</a>");

   } 

      out.write("\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"item-details-blocks\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-lg-8 col-md-7 col-12\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"single-block comments\">\r\n");
      out.write("<h3>후기글</h3>\r\n");
      out.write("<div class=\"single-comment\">\r\n");
      out.write("<img src=\"assets/images/testimonial/testi2.jpg\" alt=\"#\">\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("<h4>Luis Havens</h4>\r\n");
      out.write("<span>25 Feb, 2023</span>\r\n");
      out.write("<p>There are many variations of passages of Lorem Ipsum available, but the majority\r\n");
      out.write("have suffered alteration in some form, by injected humour, or randomised words\r\n");
      out.write("which don't look even slightly believable.</p>\r\n");
      out.write("<a href=\"javascript:void(0)\" class=\"reply\"><i class=\"lni lni-reply\"></i> Reply</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"single-block comment-form\">\r\n");
      out.write("<h3>Post a comment</h3>\r\n");
      out.write("<form action=\"#\" method=\"POST\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-lg-6 col-12\">\r\n");
      out.write("<div class=\"form-box form-group\">\r\n");
      out.write("<input type=\"text\" name=\"name\" class=\"form-control form-control-custom\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly/>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- <div class=\"col-lg-6 col-12\"> -->\r\n");
      out.write("<!-- <div class=\"form-box form-group\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<div class=\"col-12\">\r\n");
      out.write("<div class=\"form-box form-group\">\r\n");
      out.write(" <textarea name=\"#\" class=\"form-control form-control-custom\" placeholder=\"작성란\"></textarea>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-12\">\r\n");
      out.write("<div class=\"button\">\r\n");
      out.write("<button type=\"submit\" class=\"btn\">글 쓰기</button>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-4 col-md-5 col-12\">\r\n");
      out.write("<div class=\"item-details-sidebar\">\r\n");
      out.write("<div class=\"single-block author\">\r\n");
      out.write("<h3>판매처</h3>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("<img src=\"upload/shop/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.shopDto.shopImg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"#\">\r\n");
      out.write("<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.shopDto.shopName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("<span>");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("<a href=\"myProductList.do?shopId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.shopDto.shopId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"see-all\">상점 구경하러가기</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"single-block author\">\r\n");
      out.write("<h3>상품 설명</h3>\r\n");
      out.write("<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- <!-- <div class=\"single-block \"> -->\r\n");
      out.write("<!-- <h3>Location</h3> -->\r\n");
      out.write("<!-- <div class=\"mapouter\"> -->\r\n");
      out.write("<!-- <div class=\"gmap_canvas\"><iframe width=\"100%\" height=\"300\" id=\"gmap_canvas\" src=\"https://maps.google.com/maps?q=2880%20Broadway,%20New%20York&t=&z=13&ie=UTF8&iwloc=&output=embed\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe><a href=\"https://putlocker-is.org\"></a><br> -->\r\n");
      out.write("<!-- <style> -->\r\n");
      out.write("<!--                                             .mapouter { -->\r\n");
      out.write("<!--                                                 position: relative; -->\r\n");
      out.write("<!--                                                 text-align: right; -->\r\n");
      out.write("<!--                                                 height: 300px; -->\r\n");
      out.write("<!--                                                 width: 100%; -->\r\n");
      out.write("<!--                                             } -->\r\n");
      out.write("<!--                                         </style><a href=\"https://www.embedgooglemap.net\">google map code for website</a> \r\n");
      out.write("<!-- <style> -->\r\n");
      out.write("<!--                                             .gmap_canvas { -->\r\n");
      out.write("<!--                                                 overflow: hidden; -->\r\n");
      out.write("<!--                                                 background: none !important; -->\r\n");
      out.write("<!--                                                 height: 300px; -->\r\n");
      out.write("<!--                                                 width: 100%; -->\r\n");
      out.write("<!--                                             } -->\r\n");
      out.write("<!--                                         </style> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<!-- </div> --> \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer-bottom\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"inner\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-12\">\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("<p class=\"copyright-text\">Designed and Developed by 1조\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"scroll-top btn-hover\">\r\n");
      out.write("<i class=\"fas fa-arrow-up\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<script data-cfasync=\"false\" src=\"/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/wow.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/tiny-slider.js\"></script>\r\n");
      out.write("<script src=\"resources/js/glightbox.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        const current = document.getElementById(\"current\");\r\n");
      out.write("        const opacity = 0.6;\r\n");
      out.write("        const imgs = document.querySelectorAll(\".img\");\r\n");
      out.write("        imgs.forEach(img => {\r\n");
      out.write("            img.addEventListener(\"click\", (e) => {\r\n");
      out.write("                //reset opacity\r\n");
      out.write("                imgs.forEach(img => {\r\n");
      out.write("                    img.style.opacity = 1;\r\n");
      out.write("                });\r\n");
      out.write("                current.src = e.target.src;\r\n");
      out.write("                //adding class \r\n");
      out.write("                //current.classList.add(\"fade-in\");\r\n");
      out.write("                //opacity\r\n");
      out.write("                e.target.style.opacity = opacity;\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/productDetail.jsp(73,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who eq 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<li class=\"nav-item\">\r\n");
          out.write("<a class=\" dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-4\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">관리자페이지</a>\r\n");
          out.write("<ul class=\"sub-menu mega-menu collapse\" id=\"submenu-1-4\">\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("<li class=\"mega-menu-title\">회원</li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"newMemberList.do\">회원 승인</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"memberList.do\">회원 리스트</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"delMemberList.do\">탈퇴 회원</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("<li class=\"mega-menu-title\">상점</li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"newShopList.do\">신규 상점</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"shopList.do\">상점 리스트</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"delShopList.do\">상점 삭제</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/productDetail.jsp(96,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who eq 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<li class=\"nav-item\">\r\n");
          out.write("\r\n");
          out.write("<a class=\" dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-4\" \r\n");
          out.write("aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">마이페이지</a>\r\n");
          out.write("\r\n");
          out.write("<ul class=\"sub-menu mega-menu collapse\" id=\"submenu-1-4\">\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPage.do\">마이페이지</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPageUpdateForm.do?\">정보수정</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPageDelete.do\">회원탈퇴</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/productDetail.jsp(114,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who eq 2 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<li class=\"nav-item\">\r\n");
          out.write("<a class=\" dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-4\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">마이페이지</a>\r\n");
          out.write("<ul class=\"sub-menu mega-menu collapse\" id=\"submenu-1-4\">\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("<li class=\"mega-menu-title\">상점</li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myShop.do\">내 상점 보기</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myShopAddForm.do\">상점 추가</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("<li class=\"mega-menu-title\">마이페이지</li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPage.do\">마이페이지</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPageUpdateForm.do\">정보수정</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPageDelete.do\">회원탈퇴</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/productDetail.jsp(136,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/productDetail.jsp(284,6) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy/MM/dd");
      // /WEB-INF/views/productDetail.jsp(284,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.shopDto.openDate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
