/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-06-02 00:42:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;
import java.util.List;
import com.yogi.hoxy.dtos.MemberShoppingDto;
import com.yogi.hoxy.utils.Utils;
import com.yogi.hoxy.dtos.ProductDto;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1617260074751L));
    _jspx_dependants.put("jar:file:/D:/src/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AdminProjects_f/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/src/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AdminProjects_f/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.yogi.hoxy.dtos.ProductDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.yogi.hoxy.utils.Utils");
    _jspx_imports_classes.add("com.yogi.hoxy.dtos.MemberShoppingDto");
    _jspx_imports_classes.add("java.util.Map");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
 List<ProductDto> list = (List<ProductDto>) request.getAttribute("list"); 
      out.write('\r');
      out.write('\n');
 List<MemberShoppingDto> msList = (List<MemberShoppingDto>) request.getAttribute("msList"); 
      out.write('\r');
      out.write('\n');
 List<Map<String, String>> pList = (List<Map<String, String>>) request.getAttribute("pList"); 
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<title>상품리스트</title>\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/images/favicon.svg\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("// function se(){\r\n");
      out.write("// \tvar keyword = $(\"#keyword\").val();\r\n");
      out.write("// \tif(keyword == ''){\r\n");
      out.write("// \t\talert(\"검색어를 입력하세요\");\r\n");
      out.write("// \t\treturn;\r\n");
      out.write("// \t}\r\n");
      out.write("//  \t$.ajax({\r\n");
      out.write("//  \t\tmethod:\"post\",\r\n");
      out.write("//  \t\turl: \"ch.do\",\r\n");
      out.write("//  \t\tdata: {\"keyword\": keyword},\r\n");
      out.write("//  \t\tdataType:\"json\",\r\n");
      out.write("//  \t\tasync:false,\r\n");
      out.write("//  \t\tsuccess:function(data){\r\n");
      out.write("//  \t\t\talert(data[\"list\"][0][\"product_seq\"]);\r\n");
      out.write("//  \t\t\tfor(var i=0;i<data[\"list\"].length;i++){\r\n");
      out.write("//  \t\t\t\t$(\".w\").append(\r\n");
      out.write("//   \t\t\t\t\t\t'<div class=\"col-lg-4 col-md-6 col-12\">' +\r\n");
      out.write("//   \t\t\t\t\t\t'<div class=\"single-item-grid\">'+\r\n");
      out.write("//   \t\t\t\t\t\t'<div class=\"image\">'+\r\n");
      out.write("//  \t\t\t\t\t\t'<a href=\"productDetail.do?product_Seq='+ data[\"list\"][i][\"product_seq\"] + '\"><img src=\"upload/product/+'data[list][i][\"img_Url\"]'+\" alt=\"productImg\"></a>'+\r\n");
      out.write("//   \t\t\t\t\t\t'<i class=\" cross-badge lni lni-bolt\"></i>'+\r\n");
      out.write("//   \t\t\t\t\t\t'<span class=\"flat-badge sale\">'+\r\n");
      out.write("//   \t\t\t\t\t\t'</span>'+\r\n");
      out.write("//   \t\t\t\t\t\t'</div>'+\r\n");
      out.write("//   \t\t\t\t\t\t'<div class=\"content\">'+\r\n");
      out.write("//  \t\t\t\t\t\t'<a href=\"javascript:void(0)\" class=\"tag\">data[\"list\"][i][\"category\"]</a>'+\r\n");
      out.write("//   \t\t\t\t\t\t'<h3 class=\"title\">'+\r\n");
      out.write("//  \t\t\t\t\t\t'<a href=\"item-details.html\">'data[\"list\"][i][\"productName\"]'</a>'+\r\n");
      out.write("//   \t\t\t\t\t\t'</h3>'+\r\n");
      out.write("//   \t\t\t\t\t\t'<p class=\"location\"><a href=\"javascript:void(0)\"><i class=\"lni lni-map-marker\">'+\r\n");
      out.write("//  \t\t\t\t\t\t'</i>data[\"list\"][i][\"shopName\"] / data[\"list\"][i][\"local\"]</a></p>'+\r\n");
      out.write("\r\n");
      out.write("//  \t\t\t\t\t\t'<ul class=\"info\">'+\r\n");
      out.write("//  \t\t\t\t\t\t'<li class=\"price\">data[\"list\"][i][\"price\"]</li>'+\r\n");
      out.write("//  \t\t\t\t\t\t'<li class=\"like\"><a href=\"javascript:void(0)\">data[\"list\"][i][\"like\"]♥<i class=\"lni lni-heart\"></i></a>'+\r\n");
      out.write("//   \t\t\t\t\t\t'</li>'+\r\n");
      out.write("//   \t\t\t\t\t\t'</ul>'+\r\n");
      out.write("//   \t\t\t\t\t\t'</div>'+\r\n");
      out.write("//   \t\t\t\t\t\t'</div>'+\r\n");
      out.write("//   \t\t\t\t\t\t'</div>'\r\n");
      out.write("//  \t\t\t\t);\r\n");
      out.write("//  \t\t\t}\r\n");
      out.write("//  \t\t},\r\n");
      out.write("//  \t\terror:function(){\r\n");
      out.write("//  \t\t\talert(\"그런건 없어요.\");\r\n");
      out.write("//  \t\t}\r\n");
      out.write("//  \t});\r\n");
      out.write("// }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Lato&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/LineIcons.2.0.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/animate.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/tiny-slider.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/glightbox.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/main.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("      <p class=\"browserupgrade\">\r\n");
      out.write("        You are using an <strong>outdated</strong> browser. Please\r\n");
      out.write("        <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve\r\n");
      out.write("        your experience and security.\r\n");
      out.write("      </p>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"preloader\">\r\n");
      out.write("<div class=\"preloader-inner\">\r\n");
      out.write("<div class=\"preloader-icon\">\r\n");
      out.write("<span></span>\r\n");
      out.write("<span></span>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"header navbar-area\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("<div class=\"col-lg-12\">\r\n");
      out.write("<div class=\"nav-inner\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("<a class=\"navbar-brand\" href=\".\">\r\n");
      out.write("<img src=\"upload/logo.jpg\" alt=\"Logo\">\r\n");
      out.write("</a>\r\n");
      out.write("<button class=\"navbar-toggler mobile-menu-btn\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("<span class=\"toggler-icon\"></span>\r\n");
      out.write("<span class=\"toggler-icon\"></span>\r\n");
      out.write("<span class=\"toggler-icon\"></span>\r\n");
      out.write("</button>\r\n");
      out.write("<div class=\"collapse navbar-collapse sub-menu-bar\" id=\"navbarSupportedContent\">\r\n");
      out.write("<ul id=\"nav\" class=\"navbar-nav ms-auto\">\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\".\" aria-label=\"Toggle navigation\">홈</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write(" <a href=\"search.do\" class=\"active\" aria-label=\"Toggle navigation\">카테고리</a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</div> \r\n");
      out.write("<div class=\"login-button\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li>\r\n");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</nav> \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div> \r\n");
      out.write("</div> \r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"breadcrumbs\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("<div class=\"breadcrumbs-content\">\r\n");
      out.write("<h1 class=\"page-title\">상품 페이지</h1>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("<ul class=\"breadcrumb-nav\">\r\n");
      out.write("<li><a href=\".\">Home</a></li>\r\n");
      out.write("<li>상품 페이지</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"category-page section\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-lg-3 col-md-4 col-12\">\r\n");
      out.write("<div class=\"category-sidebar\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"single-widget search\">\r\n");
      out.write("<h3>상품 검색하기</h3>\r\n");
      out.write("<form method=\"post\" action=\"search.do\">\t\r\n");
      out.write("<input type=\"text\" name=\"keyword\" id=\"keyword\" placeholder=\"검색어를 입력하세요...\">\r\n");
      out.write("<button type=\"submit\" ><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"single-widget\">\r\n");
      out.write("<h3>카테고리</h3>\r\n");
      out.write("<ul class=\"list\">\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"search.do?category=식품\"><i class=\"fas fa-utensils\"></i> 식품\r\n");
      out.write("<span>\r\n");

boolean result = false;
int cC1 = 0;
for(Map<String, String> count : pList){
	if(count.get("category").equals("식품")){
		result = true;
		cC1 = Integer.parseInt(String.valueOf(count.get("count")));
	}
}
	if(result){
		
      out.print(cC1 );

	} else {
		
      out.write('0');

	}

      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"search.do?category=유아\"><i class=\"fas fa-child\"></i> 유아\r\n");
      out.write("<span>\r\n");

int cC2 = 0;
for(Map<String, String> count : pList){
	if(count.get("category").equals("유아")){
		result = true;
		cC2 = Integer.parseInt(String.valueOf(count.get("count")));
	}
}
	if(result){
		
      out.print(cC2 );

	} else {
		
      out.write('0');

	}

      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"search.do?category=식음료\"><i class=\"fas fa-wine-glass-alt\"></i> 식음료\r\n");
      out.write("<span>\r\n");

int cC3 = 0;
for(Map<String, String> count : pList){
	if(count.get("category").equals("식음료")){
		result = true;
		cC3 = Integer.parseInt(String.valueOf(count.get("count")));
	}
}
	if(result){
		
      out.print(cC3 );

	} else {
		
      out.write('0');

	}

      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"search.do?category=전자기기\"><i class=\"fas fa-plug\"></i> 전자기기\r\n");
      out.write("<span>\r\n");

int cC4 = 0;
for(Map<String, String> count : pList){
	if(count.get("category").equals("전자기기")){
		result = true;
		cC4 = Integer.parseInt(String.valueOf(count.get("count")));
	}
}
	if(result){
		
      out.print(cC4 );

	} else {
		
      out.write('0');

	}

      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"search.do?category=뷰티\"><i class=\"fas fa-spray-can\"></i> 뷰티\r\n");
      out.write("<span>\r\n");

int cC5 = 0;
for(Map<String, String> count : pList){
	if(count.get("category").equals("뷰티")){
		result = true;
		cC5 = Integer.parseInt(String.valueOf(count.get("count")));
	}
}
	if(result){
		
      out.print(cC5 );

	} else {
		
      out.write('0');

	}

      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"search.do?category=의약품\"><i class=\"fas fa-capsules\"></i> 의약품\r\n");
      out.write("<span>\r\n");

int cC6 = 0;
for(Map<String, String> count : pList){
	if(count.get("category").equals("의약품")){
		result = true;
		cC6 = Integer.parseInt(String.valueOf(count.get("count")));
	}
}
	if(result){
		
      out.print(cC6 );

	} else {
		
      out.write('0');

	}

      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"search.do?category=의류\"><i class=\"fas fa-tshirt\"></i> 의류\r\n");
      out.write("<span>\r\n");

int cC7 = 0;
for(Map<String, String> count : pList){
	if(count.get("category").equals("의류")){
		result = true;
		cC7 = Integer.parseInt(String.valueOf(count.get("count")));
	}
}
	if(result){
		
      out.print(cC7 );

	} else {
		
      out.write('0');

	}

      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-9 col-md-8 col-12\">\r\n");
      out.write("<div class=\"category-grid-list\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-12\">\r\n");
      out.write("<div class=\"category-grid-topbar\">\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("<h3 class=\"title\">상품리스트</h3>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("<nav>\r\n");
      out.write("<div class=\"nav nav-tabs\" id=\"nav-tab\" role=\"tablist\">\r\n");
      out.write("<form>\r\n");
      out.write("<p><a href=\"search.do?order=price\">저렴순</a>&nbsp;&nbsp;&nbsp;</p>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"tab-content\" id=\"nav-tabContent\">\r\n");
      out.write("<div class=\"tab-pane fade show active\" id=\"nav-grid\" role=\"tabpanel\" aria-labelledby=\"nav-grid-tab\">\r\n");
      out.write("<div class=\"row w\">\r\n");

if(list == null || list.size() == 0){
	
      out.write("<h1>관련상품이 없습니다.</h1>>");

	} else {
	for(ProductDto dto : list){
int stock = Integer.parseInt(dto.getStock());

      out.write("\r\n");
      out.write("<div class=\"col-lg-4 col-md-6 col-12\">\r\n");
      out.write("<div class=\"single-item-grid\">\r\n");
      out.write("<div class=\"image\">\r\n");
      out.write("<a href=\"productDetail.do?product_seq=");
      out.print(dto.getProduct_seq());
      out.write("\"><img src=\"upload/product/");
      out.print(dto.getImg_Url() );
      out.write("\" alt=\"productImg\"></a>\r\n");
      out.write("<i class=\" cross-badge lni lni-bolt\"></i>\r\n");
 if(stock <= 1){
	
      out.write("<span class=\"flat-badge sale\">재고 : ");
      out.print(stock );
      out.write("</span> ");

} else {
	
      out.write("<span class=\"flat-badge rent\"> 재고 : ");
      out.print(stock );
      out.write("</span>\r\n");

}

      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("<a href=\"javascript:void(0)\" class=\"tag\">");
      out.print(dto.getCategory() );
      out.write("</a>\r\n");
      out.write("<h3 class=\"title\">\r\n");
      out.write("<a>");
      out.print(dto.getProductName() );
      out.write("</a>\r\n");
      out.write("</h3>\r\n");
      out.write("<p class=\"location\"><a href=\"javascript:void(0)\">");
      out.print(dto.getShopDto().getShopName());
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(dto.getShopDto().getLocal() );
      out.write("</a></p>\r\n");
      out.write("<ul class=\"info\">\r\n");
      out.write("<li class=\"price\">");
      out.print(Utils.comma(dto.getPrice()));
      out.write("원</li>\r\n");
 if(msList == null || msList.size() == 0){
	
      out.write("<li class=\"like\"><a href=\"like.do?product_seq=");
      out.print(dto.getProduct_seq());
      out.write("\">찜고</a></li>");

}else if(msList != null){
	boolean isS = false;
	for(MemberShoppingDto msdto : msList){
		if(msdto.getProduct_seq() == dto.getProduct_seq()){
			isS = true;	
		} 
	} 
	if(isS){
	
      out.write("\t<li class=\"like\"><a href=\"deleteLikeList.do?product_seq=");
      out.print(dto.getProduct_seq());
      out.write("\">찜X</a></li> ");

	} else {
		
      out.write("<li class=\"like\"><a href=\"like.do?product_seq=");
      out.print(dto.getProduct_seq());
      out.write("\">찜고</a></li>");
	
	}
}  

      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\t\r\n");

	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 어팬드 - 제이쿼리 마지막에 계속 추가해주는  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer-bottom\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"inner\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-12\">\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("<p class=\"copyright-text\">Designed and Developed by 1조\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"scroll-top btn-hover\">\r\n");
      out.write("<i class=\"fas fa-arrow-up\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<script data-cfasync=\"false\" src=\"/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/wow.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/tiny-slider.js\"></script>\r\n");
      out.write("<script src=\"resources/js/glightbox.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/search.jsp(125,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who eq 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<li class=\"nav-item\">\r\n");
          out.write("<a class=\" dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-4\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">관리자페이지</a>\r\n");
          out.write("<ul class=\"sub-menu mega-menu collapse\" id=\"submenu-1-4\">\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("<li class=\"mega-menu-title\">회원</li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"newMemberList.do\">회원 승인</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"memberList.do\">회원 리스트</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"delMemberList.do\">탈퇴 회원</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("<li class=\"mega-menu-title\">상점</li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"newShopList.do\">신규 상점</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"shopList.do\">상점 리스트</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"delShopList.do\">상점 삭제</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/search.jsp(148,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who eq 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<li class=\"nav-item\">\r\n");
          out.write("\r\n");
          out.write("<a class=\" dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-4\" \r\n");
          out.write("aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">마이페이지</a>\r\n");
          out.write("\r\n");
          out.write("<ul class=\"sub-menu mega-menu collapse\" id=\"submenu-1-4\">\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPage.do\">마이페이지</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPageUpdateForm.do?\">정보수정</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPageDelete.do\">회원탈퇴</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/search.jsp(166,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who eq 2 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<li class=\"nav-item\">\r\n");
          out.write("<a class=\" dd-menu collapsed\" href=\"javascript:void(0)\" data-bs-toggle=\"collapse\" data-bs-target=\"#submenu-1-4\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">마이페이지</a>\r\n");
          out.write("<ul class=\"sub-menu mega-menu collapse\" id=\"submenu-1-4\">\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("<li class=\"mega-menu-title\">상점</li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myShop.do\">내 상점 보기</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myShopAddForm.do\">상점 추가</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("<li class=\"single-block\">\r\n");
          out.write("<ul>\r\n");
          out.write("<li class=\"mega-menu-title\">마이페이지</li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPage.do\">마이페이지</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPageUpdateForm.do\">정보수정</a></li>\r\n");
          out.write("<li class=\"nav-item\"><a href=\"myPageDelete.do\">회원탈퇴</a></li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          out.write("</ul>\r\n");
          out.write("</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/search.jsp(188,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/search.jsp(198,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<a href=\"login.do\"><i class=\"fas fa-sign-in-alt\"></i> 로그인</a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/search.jsp(204,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<a href=\"registration.html\"><i class=\"fas fa-user-plus\"></i> 회원가입</a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /WEB-INF/views/search.jsp(207,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<a href=\"logout.do\"><i class=\"fas fa-sign-out-alt\"></i> 로그아웃</a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }
}
